### ISSUE TITLE
Waterbird Foraging Survey

### ISSUE THREAD

**Issue by stephenfuqua** [FlightNode/FlightNode.Api#26]
As a Volunteer, I want to submit a foraging survey, so that project coordinators can compile scientific data on birds foraging behavior at a site.

**Comment by stephenfuqua** [comment]
Depends on #25.

[ ] Basic user interface
[ ] API
[ ] Add map to UI if possible

**Comment by stephenfuqua** [comment]
## Review comments

### Page 1
- Calendar control for date
- Time control for times
- Entered 1/1/00 for date, start time came out as `2015-03-25T16:11:11.011Z`
  - UTC is good
  - But where did the date come from?
- Probably need to add some validations such as end time after start time
- Pending record saved, but missing these fields that are displayed on the screen:
  - Start temperature (End _should_ be null)
  - Wind Speed
  - Tide - shouldn't this be two different questions? Check notes from March meeting, _which were never communicated to KP_.
  - Observers - needs to be just a list in the survey table rather than an outright table, as not all observers will be system users.
- Protect against HTML in the observers.

### Page 2
- Did not # of juveniles in Bin 2, but everything else appeared to save.
- Need to be able to add birds that are not in the default list.
- Protect against HTML in the comments
- Clicked Next and it did not move to third page - just reloaded second page. In fact, appears to have created a new survey record.

### Back button to Page 1
- Does not reload data.

**Comment by stephenfuqua** [comment]
In a meeting with users back in March, I learned:
- Creating the form to read top to bottom, without left to right is good. However, it will be best to keep the element order consistent with the paper form in order to streamline copying of data from one to the other.
- If "New Colony" is selected, then the user needs to be able to input information about the location. But leave out Site Code, as this will be entered by an administrator (_new functionality_: admin will probably want to know about new sites on a dashboard!).
- Time of nearest low tide is not needed.
- Tidal information has two different settings, each of which needs three options:
  - Water Height: Appears High, Normal, Appears Low
  - (?Driven By?): Tidal, Wind, None
- On step 2, allow manual addition of birds using common name.
- Make sure that the following are added to the bird list if not already there:
  - UNKN - unknown
  - SPSP - Sandpiper species / peep
  - HESP - Heron species
- For "Other" on the disturbance page, instruct user to enter that into the comments field.

**Comment by stephenfuqua** [comment]
Need to change to query for all the different attributes, e.g. tides, water, etc., instead of using the temporary hard-coding in `censusFormService`. This is likely why saving some of these values failed previously.

**Comment by stephenfuqua** [comment]
I wrote a controller that returns all of the "enums" for tides, weather, etc. But loading radio and select buttons dynamically can be slow, even with async actions. Might need to switch that back.

Either way, I have now broken the location selection and must fix that.

**Comment by stephenfuqua** [comment]
What about timezone? Does it matter in this case? Might need to ask users about this.

**Comment by kpunjani** [comment]
Entered 1/1/00 for date, start time came out as 2015-03-25T16:11:11.011Z
UTC is good
But where did the date come from?

Answer to this is I have hard coded start date and end date in the censusFormService in order to make the front to back integration work. The date format which the date control was returning was not compatible with back end date format.
